version: "3.7"

services:
  
  whoami:
    image: "containous/whoami"
    container_name: "whoami"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${BASE_DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=sslbot"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.services.whoami.loadbalancer.passhostheader=true"   

    env_file:
      - ${PWD}/config/ssl